---

- name: configure https nginx
  template:
    src: "https.conf.j2"
    dest: "{{ nginx_root }}/https-{{ domain_base }}.conf"
  register: nginx_config_changed

- name: create diffie-hellman group
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

- name: start nginx https container
  docker_container:
    name: ansible-nginx-https
    image: nginx:1.11
    ports:
    - "443:443"
    volumes:
    - "/etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem"
    - "{{ nginx_root }}/https-{{ domain_base }}.conf:/etc/nginx/conf.d/default.conf"
    - "/etc/letsencrypt/live/jenkins.{{ domain_base }}/fullchain.pem:/etc/nginx/cert.crt"
    - "/etc/letsencrypt/live/jenkins.{{ domain_base }}/privkey.pem:/etc/nginx/cert.key"
    - "{{ nginx_root }}/html:/usr/share/nginx/html"
    links:
    - "ansible-jenkins:jenkins"

...
