---

- name: create nginx home dirs
  file:
    path: "{{ nginx_root }}/html"
    state: directory
    mode: 0755

- name: install epel repo
  yum:
    name: epel-release
    state: present

- name: install packages for host
  yum: name={{ item }} state=present update_cache=yes
  with_items:
  - certbot

- debug: var=domain_base

- debug: msg="{{ lookup('env', 'PROVISIONER_DOMAIN_BASE') }}"

- name: configure http nginx
  template:
    src: "http.conf.j2"
    dest: "{{ nginx_root }}/http-{{ domain_base }}.conf"
  register: nginx_config_changed

- name: start nginx http container
  docker_container:
    name: ansible-nginx-http
    image: nginx:1.11
    ports:
    - "80:80"
    volumes:
    - "{{ nginx_root }}/http-{{ domain_base }}.conf:/etc/nginx/conf.d/default.conf"
    - "{{ nginx_root }}/html:/usr/share/nginx/html"

- name: get certs
  command: "certbot certonly --webroot -w /srv/docker/nginx/html/ -d {{ item.domain_name }}.{{ domain_base}} creates=/etc/letsencrypt/live/{{ item.domain_name }}.{{ domain_base }}/fullchain.pem --agree-tos --non-interactive --email {{ email }}"
  with_items:
    - "{{ websites }}"


...
