---

- name: install packages
  yum: name={{ item }} state=present
  with_items:
  - java-1.8.0-openjdk-headless
  - git

- name: add jenkins user
  user:
    name: jenkins
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
    groups: dockerroot
    append: yes

- name: link authorized keys
  file:
    src: /home/jenkins/.ssh/id_rsa.pub
    dest: /home/jenkins/.ssh/authorized_keys
    state: link

- name: create jenkins home dirs
  file:
    path: "{{ jenkins_home }}"
    state: directory
    mode: 0755
    owner: 1000

- name: start jenkins container
  docker_container:
    name: ansible-jenkins
    image: jenkins:2.7.2
    volumes:
    - "/home/jenkins:/mount/home"
    - "{{ jenkins_home }}:/var/jenkins_home"
  register: jenkins_started

